### ISSUE TITLE
[help] How to close the current open Deol buffer?

### ISSUE THREAD

**Issue by dhelbegor** [Shougo/deol.nvim#16]
I'm trying to close the open Deol buffer, actually to do that I'm using $ exit + esc + :db, can you guyes tell me how can I close the buffer with correctly please??

**Comment by Shougo** [comment]
> $ exit + esc + :db

`:bd`?

> can you guyes tell me how can I close the buffer with correctly please??

You should use `<Plug>(deol_quit)` mapping instead.
It is mapped to `q` key in default.
