### ISSUE TITLE
Keyboard navigation

### ISSUE THREAD

**Issue by tnguyen14** [Shougo/deol.nvim#17]
When in a terminal session window, I cannot use my up/down arrow keys to go to previous commands. When I do, I get the error:

```
E21: Cannot make changes, 'modifiable' is off
```

Is there a way I can easily navigate to previous terminal commands?

**Comment by tnguyen14** [comment]
This turns out to be similar to https://github.com/vim/vim/issues/2716

I ended up removing the mapping of `Esc` to `<C-\><C-n`, and mapped that to `<C-n>` instead.

**Comment by Shougo** [comment]
Reproduced in Vim8.
But it works for me in neovim.  Unfortunately, it seems feature of Vim8.

I recommend for you to use neovim.

**Comment by Shougo** [comment]
In Vim8, it works for me.

```vim
    tnoremap   <ESC>       <C-w>N
    tnoremap   <ESC><ESC>  <C-w>N
```

https://github.com/vim/vim/issues/2716#issuecomment-445693815

**Comment by tnguyen14** [comment]
Thanks for that. I didn't understand that comment, but putting that in works.

I use neovim usually, which is great, but only have vim8 at work.
