### ISSUE TITLE
How to escape from vim inside a Deol session

### ISSUE THREAD

**Issue by tnguyen14** [Shougo/deol.nvim#18]
Inside a Deol session, can I "escape" a vim session? This is an issue because my "git commit" would bring up vim as the `GIT_EDITOR`, and I can't seem to write in that vim session.

**Comment by Shougo** [comment]
What is your environment?
Please describe it for me.

If you use neovim, you should install neovim-remote.
https://github.com/mhinz/neovim-remote

If you use Vim8, you should install GVim.

**Comment by tnguyen14** [comment]
I am using Vim8, but no GVim. How would GVim enable this?

**Comment by Shougo** [comment]
> How would GVim enable this?

You should research it instead.

> What is your environment?

How do you install Vim8?

**Comment by Shougo** [comment]
> Inside a Deol session, can I "escape" a vim session? This is an issue because my "git commit" would bring up vim as the GIT_EDITOR, and I can't seem to write in that vim session.

You should check your Vim's terminal configuration.
Because, in default behavior `<ESC>` works as internal Vim's `<ESC>`.

So it works as like.
`<ES>:wq` exists your inside Vim and returns command line.

**Comment by tnguyen14** [comment]
When I do `ESC` in that, it seems to send the Esc to Deol's session, not the git editing's session.

**Comment by Shougo** [comment]
You should check `verbose tnoremap <ESC>`.
You have overwrite `<ESC>` mapping.
