### ISSUE TITLE
インサートモード移行時、カーソル位置を復元する機能

### ISSUE THREAD

**Issue by hrsh7th** [Shougo/deol.nvim#2]
## 概要
- neovim の terminal は insert-mode に入る時に、カーソル位置が下記のようになります。
    - インサートモードにおける最終位置
    - 最初の場合は末尾
- これは通常の vim の動きとは違うので使いづらいと考えています。

## 要望
- 特定のプロンプト上で `i` などでインサートモードに入った場合にカーソル位置を復元する機能が欲しいです。
- 雑な実装は以下です。

```VimL
  autocmd! TermOpen term://* call MyTermOpenSetting()
  function! MyTermOpenSetting()
    tnoremap <buffer><Esc> <C-\><C-n>
    nnoremap <buffer><expr>i MyMoveCursor()
  endfunction
  function! MyMoveCursor()
    let pos = getcurpos()
    return "i\<End>" . repeat("\<Left>", strlen(getline(pos[1])) - pos[2] + 1)
  endfunction
```

**Comment by Shougo** [comment]
検討しておきます。

**Comment by hrsh7th** [comment]
使ってみましたが完璧でした。ありがとうございます。

**Comment by Shougo** [comment]
余談ですが、私の環境では `<Home>`, `<End>` がうまく動かず調整に苦労しました。
