### ISSUE TITLE
Don't only close DeolEdit window but also Deol terminal window by `<Plug>(deol_quit)`

### ISSUE THREAD

**Issue by ujihisa** [Shougo/deol.nvim#22]
## Proposed expected behaviour

`:DeolEdit` opens 2 windows; terminal and deol-edit. When I type `<Plug>(deol_quit)`, it closes both the terminal and deol-edit windows.

## Current actual behaviour

`:DeolEdit` opens 2 windows; terminal and deol-edit. When I type `<Plug>(deol_quit)`, it only closes the deol-edit window.

**Comment by Shougo** [comment]
Fixed.

**Comment by ujihisa** [comment]
Thx! b7e8c280c599e93de2d06b78787f371e0cb3db81 af865c60e24c37aaf3315cccbf8ccbd269d5f502 (not 72 but 22)
