### ISSUE TITLE
How to have the deol-edit buffer use coc completion?

### ISSUE THREAD

**Issue by pearagit** [Shougo/deol.nvim#23]
To start off, I'm using `zsh`, `neovim`, and `neovim-remote`, and `deol.nvim` to open a zsh terminal inside of neovim. For completion/suggestion/etc, I'm using `coc.nvim`.

When `<Plug>(deol_edit)` is executed, the filetype is set to zsh but no completion or suggestions appear. However when the current command is edited via `edit-command-liine`, coc completion does work.

Here's a recording to illustrate:
https://asciinema.org/a/y868ZF6Gy3pxpmXNUOhkgZxtQ

Let me know if there's anything I can clarify, or if this is working as intended.

Thank!

**Comment by Shougo** [comment]
I don't support coc in deol.

I use deoplete + deoplete-zsh in deol and it work well.
https://github.com/deoplete-plugins/deoplete-zsh

**Comment by Shougo** [comment]
> However when the current command is edited via edit-command-liine, coc completion does work.

I don't understand.  We have no ESP skills.
