### ISSUE TITLE
command name completion does not at deol-edit buffer with bash

### ISSUE THREAD

**Issue by ujihisa** [Shougo/deol.nvim#36]
https://github.com/Shougo/deol.nvim/blob/0c6e1653f0d0a904efa8da01e470ffe0bd1bf594/doc/deol.txt#L56

Even with deoplete-zsh plugin, command name completion does not work. It seems to that deol is expecting deoplete-zsh to provide bash completion, but deoplete-zsh does not seem to provide it, and I don't think it's an issue in deoplete-zsh since it focuses on zsh, but it's an integration issue in deol-edit.

**Comment by Shougo** [comment]
```vim
call deoplete#custom#option({
      \ 'nofile_complete_filetypes': ['bash', 'zsh', 'denite-filter'],
      \ })
call deoplete#custom#source('zsh', 'filetypes', ['zsh', 'bash'])
```

It works for me.
