### ISSUE TITLE
"[No Name]" buffer is created when deol#start() fires

### ISSUE THREAD

**Issue by glassesneo** [Shougo/deol.nvim#44]
**Warning: I will close the issue without the minimal init.vim and the
reproduction instructions.**

# Problems summary
neovimを起動後、二回目以降のdeol#start()でNo Nameのバッファが生成される

## Environment Information (Required!)
- deol.nvim version(SHA-1):
c77537a563a58221eb996ea64304dbe22ebc6f64

- OS:
MacOS Sonoma 14.5 (M1, 2020)

- neovim/Vim `:version` output:
NVIM v0.10.0
Build type: Release
LuaJIT 2.1.1713484068

## config
```toml
[[plugins]]
repo = 'Shougo/deol.nvim'
on_map = { n = '<Leader>d' }
hooks_file = '$BASE_DIR/hooks/deol.lua'
```

```lua
-- deol.lua
--- lua_source {{{
local utils = require("utils")

vim.g["deol#floating_border"] = "rounded"
utils.map("n", "<Leader>d", function()
  vim.fn["deol#start"]({
    split = "farright",
    start_insert = true,
    toggle = true,
    winwidth = 45,
  })
end)
--- }}}

```

## How to reproduce the problem from neovim/Vim startup (Required!)

1. neovim起動後、deol#start()でターミナルを起動
2. 一旦ターミナルのウィンドウをquitやtoggleで閉じ、再び起動

## Screen shot

https://github.com/Shougo/deol.nvim/assets/61031352/a0770776-8174-4f99-88f7-47dd49cc0153

動画内では`deol#start()`にマッピングしているC-dを連打しています

**Comment by Shougo** [comment]
Fixed.  Please update deol.nvim.
