### ISSUE TITLE
How to navigate throught the output?

### ISSUE THREAD

**Issue by aemonge** [Shougo/deol.nvim#6]
I just moved from vim-shell into here. The integration with ZSH over here is fantastic !!!!   I'm seriously considering to use this as a default terminal. 

But I don't know how to navigate through the terminals output, the only way I can exit the terminal is by `<c-c>` , but that exists the process complete. 

So If I need to copy the output of `ls` I can't.

Any ideas ?

I've read the help document, but I couldn't find anything, i thought this might help:
```
e			<Plug>(deol_edit)
```

But `e` nor `:DeolEdit` outputs anything nor turns changes the mode.

**Comment by Shougo** [comment]
```vim
  tnoremap   <ESC>      <C-\><C-n>
```

**Comment by Shougo** [comment]
It is same of Vim8 and neovim terminal feature.

**Comment by aemonge** [comment]
So cool !!!!

Now I have a dream terminal with this combination !!!

If possible, link this wonderfull partner for this plugin in the readme ;)

https://github.com/mhinz/neovim-remote/issues/85

**Comment by Shougo** [comment]
The pull request is wellcome.
The documentation is WIP.

**Comment by aemonge** [comment]
I'll help after I finish a house moving that I need to do for the end of this month
